// Generated by `bun init`

declare namespace NodeJS {
  interface ProcessEnv {
    PUBLIC_BACKEND_URL?: string;
    PUBLIC_FIREBASE_API_KEY?: string;
    PUBLIC_FIREBASE_AUTH_DOMAIN?: string;
    PUBLIC_FIREBASE_PROJECT_ID?: string;
    PUBLIC_FIREBASE_STORAGE_BUCKET?: string;
    PUBLIC_FIREBASE_MESSAGING_SENDER_ID?: string;
    PUBLIC_FIREBASE_APP_ID?: string;
  }
}

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
